name: main
on:
  push
jobs:
  auto_tag:
    runs-on: [ubuntu]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run File
        id: run_file
        run: sh ./entrypoint.sh
